services:
    postgres:
        container_name: "postgres"
        image: "postgres"
        ports:
            - 5432:5432
        volumes:
            - db_persdata:/var/lib/postgrespers
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: controle-de-tcc
        networks:
            - default
    node:
        build: .
        environment:
            NODE_ENV: production
            PORT: 8080
            DATABASE_URL: postgresql://postgres:postgres@postgres:5432/controle_de_tcc?schema=public
        volumes:
            - ./:/home/node/app
        depends_on:
            - postgres
        ports:
            - 8080:8080
        networks:
            - default
networks:
    default:
volumes:
    db_persdata: {}
